name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        dependencies: ['lowest', 'highest']

    name: PHP ${{ matrix.php-version }} - ${{ matrix.dependencies }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
        coverage: xdebug

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      run: |
        if [[ "${{ matrix.dependencies }}" == "lowest" ]]; then
          composer update --prefer-lowest --no-interaction --no-progress
        else
          composer install --no-interaction --no-progress
        fi

    - name: Run test suite
      run: composer run-script test

    - name: Run test suite with coverage
      if: matrix.php-version == '8.2' && matrix.dependencies == 'highest'
      run: composer run-script test-coverage

    - name: Upload coverage reports to Codecov
      if: matrix.php-version == '8.2' && matrix.dependencies == 'highest'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.2-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.2-

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Run PHPStan
      run: composer run-script analyse

    - name: Check code style
      run: composer run-script cs-fix -- --dry-run --diff

  security:
    runs-on: ubuntu-latest
    name: Security Check

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.2-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.2-

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Security check
      uses: symfonycorp/security-checker-action@v5